server:
  port: 10000
spring:
  application:
    name: eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://ivfzhou-ubuntu:10000/eureka
    register-with-eureka: true
    fetch-registry: false
