spring:
  datasource:
    url: jdbc:mysql://ivfzhou-ubuntu:3306/db_reserve_platform?serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 94683364
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:cn/ivfzhou/reserve_platform/*/dao/mapper/*.xml
