server:
  port: 8762
spring:
  application:
    name: eureka-server0
eureka:
  instance:
    hostname: ivfzhoudebian
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://ivfzhoudebian:8763/eureka/,http://ivfzhoudebian:8764/eureka/,http://ivfzhoudebian:8765/eureka/
